apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: web
        image: <ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/html-demo:latest
        ports:
        - containerPort: 80
