apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deploy
  namespace: dev        # âœ… Add this line
  labels:
    app: html-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-deploy
  template:
    metadata:
      labels:
        app: html-deploy
    spec:
      containers:
      - name: web
        image: kumar:latest # GitHub Actions will override this
        ports:
        - containerPort: 8080
