apiVersion: v1
kind: Service
metadata:
  name: html-deploy
  namespace: dev
spec:
  type: NodePort
  selector:
    app: html-deploy
  ports:
    - port: 80          # Service exposed port
      targetPort: 8080  # Container port
      nodePort: 30080   # Optional: specify a fixed NodePort (range 30000â€“32767)
      protocol: TCP

