name: CI-CD to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # -------------------
    # AWS LOGIN
    # -------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: ecr
      uses: aws-actions/amazon-ecr-login@v2

    # -------------------
    # BUILD + PUSH DOCKER IMAGE
    # -------------------
    - name: Build Docker Image
      run: |
        docker build -t ${{ steps.ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ steps.ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest

    # -------------------
    # SETUP KUBECONFIG
    # -------------------
    - name: Create kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig
        chmod 600 kubeconfig

    # -------------------
    # APPLY K8S MANIFESTS
    # -------------------
    - name: Deploy to Kubernetes
      run: |
        kubectl --kubeconfig=kubeconfig set image deployment/html-app html-app=${{ steps.ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest || true
        kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml
        kubectl --kubeconfig=kubeconfig apply -f k8s/service.yaml

    - name: Verify Deployment
      run: |
        kubectl --kubeconfig=kubeconfig get pods -o wide
        kubectl --kubeconfig=kubeconfig get svc -o wide
