name: Deploy to Kubeadm Kubernetes Cluster

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # --------------------------
    # AWS + ECR LOGIN
    # --------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --------------------------
    # BUILD & PUSH IMAGE
    # --------------------------
    - name: Build & Push Docker Image
      run: |
        IMAGE="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest"

        docker build -t $IMAGE .
        docker push $IMAGE

        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    # --------------------------
    # SETUP SSH TUNNEL TO CLUSTER
    # --------------------------
    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.MASTER_PUBLIC_IP }} >> ~/.ssh/known_hosts

    - name: Create SSH Tunnel
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -f -N \
        -L 6443:172.31.33.24:6443 ubuntu@${{ secrets.MASTER_PUBLIC_IP }}

    # --------------------------
    # CREATE KUBECONFIG
    # --------------------------
    - name: Create kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > kubeconfig
        chmod 600 kubeconfig

    # --------------------------
    # DEPLOY TO KUBERNETES
    # --------------------------
    - name: Update Deployment Image
      run: |
        kubectl --kubeconfig=kubeconfig set image deployment/html-app \
        html-app=$IMAGE || true

    - name: Apply Kubernetes Manifests
      run: |
        kubectl --kubeconfig=kubeconfig apply -f k8s/deployment.yaml
        kubectl --kubeconfig=kubeconfig apply -f k8s/service.yaml

    - name: Verify Deployment
      run: |
        kubectl --kubeconfig=kubeconfig get nodes
        kubectl --kubeconfig=kubeconfig get pods -o wide
        kubectl --kubeconfig=kubeconfig get svc -o wide
